parameters:
    log.root.path: '../var/log/'

services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    ApiMessageDispatcher\:
        resource: '../../../src/'
        exclude:
            - '../../../src/DependencyInjection/'
            - '../../../src/Controller/'

    ApiMessageDispatcher\Service\Logger\AbstractLogger:
        abstract: true
        class: ApiMessageDispatcher\Service\Logger\AbstractLogger
        autoconfigure: true
        autowire: true

    ApiMessageDispatcher\Service\Logger\WebServiceLoggerInterface:
        parent: ApiMessageDispatcher\Service\Logger\AbstractLogger
        class: ApiMessageDispatcher\Service\Logger\WebServiceLogger

    ApiMessageDispatcher\Service\Logger\LoggerInterface:
        parent: ApiMessageDispatcher\Service\Logger\AbstractLogger
        class: ApiMessageDispatcher\Service\Logger\Logger

    ApiMessageDispatcher\Service\Logger\SQLLogger:
        parent: ApiMessageDispatcher\Service\Logger\AbstractLogger
        class: ApiMessageDispatcher\Service\Logger\SQLLogger

    ApiMessageDispatcher\Service\Handler\MessageHandler:
        abstract: true
        class: ApiMessageDispatcher\Service\Handler\MessageHandler
        calls:
            - [setLogger, ['@ApiMessageDispatcher\Service\Logger\LoggerInterface']]
            - [setEm, ['@Doctrine\ORM\EntityManagerInterface']]
            - [setRestClient, ['@ApiMessageDispatcher\Service\RestClientInterface']]
            - [setParameters, ['@Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface']]
            - [setBus, ['@Symfony\Component\Messenger\MessageBusInterface']]
            - [initialize]
