parameters:
    log.root.path: '../var/log/'

services:

    ApiMessageDispatcher\Service\Logger\AbstractLogger:
        abstract: true
        class: ApiMessageDispatcher\Service\Logger\AbstractLogger
        calls:
            - [setRootPath, ['%log.root.path%']]

    ApiMessageDispatcher\Service\Logger\WebServiceLoggerInterface:
        parent: ApiMessageDispatcher\Service\Logger\AbstractLogger
        class: ApiMessageDispatcher\Service\Logger\WebServiceLogger

    ApiMessageDispatcher\Service\Logger\LoggerInterface:
        parent: ApiMessageDispatcher\Service\Logger\AbstractLogger
        class: ApiMessageDispatcher\Service\Logger\Logger

    ApiMessageDispatcher\Service\Logger\SQLLogger:
        parent: ApiMessageDispatcher\Service\Logger\AbstractLogger
        class: ApiMessageDispatcher\Service\Logger\SQLLogger

    ApiMessageDispatcher\Service\RestClientInterface:
        class: ApiMessageDispatcher\Service\RestClient
        autowire: true
        autoconfigure: true

    ApiMessageDispatcher\Service\Handler\MessageHandler:
        abstract: true
        class: ApiMessageDispatcher\Service\Handler\MessageHandler
        calls:
            - [setLogger, ['@ApiMessageDispatcher\Service\Logger\LoggerInterface']]
            - [setEm, ['@Doctrine\ORM\EntityManagerInterface']]
            - [setRestClient, ['@ApiMessageDispatcher\Service\RestClientInterface']]
            - [setParameters, ['@Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface']]
            - [setBus, ['@Symfony\Component\Messenger\MessageBusInterface']]
            - [initialize]
